//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace incomeAndExpenseAccounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseCategories
    {
        public int ExpenseId { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Expenses Expenses { get; set; }
    }
}
